#pragma once

#ifndef GMOD_BASE
	#error GMOD_BASE not loaded
#endif

#ifndef GMOD_LIB_HPP_PRIM
	#define GMOD_LIB_HPP_PRIM

	#include GMOD_BASES_INCLUDE_PRIM


	// Base //
	
	#include GMOD_BASE_INCLUDE_PRIM
	

	// Classes //
	
	/// Concepts ///

	#include GMOD_INCLUDE_PRIM_IS

	//// Nums ////

	#include GMOD_INCLUDE_PRIM_ISNUM
	#include GMOD_INCLUDE_PRIM_ISSNUM
	#include GMOD_INCLUDE_PRIM_ISUNUM
	#include GMOD_INCLUDE_PRIM_ISNUMBOUNDED
	
	//// Ints ////

	#include GMOD_INCLUDE_PRIM_ISINT
	#include GMOD_INCLUDE_PRIM_ISSINT
	#include GMOD_INCLUDE_PRIM_ISUINT

	//// Floats ////

	#include GMOD_INCLUDE_PRIM_ISFLOAT
	#include GMOD_INCLUDE_PRIM_ISIEEEFLOAT


	/// Properties ///

	#include GMOD_INCLUDE_PRIM_NUM_MIN
	#include GMOD_INCLUDE_PRIM_NUM_MAX


	/// Types ///

	#include GMOD_INCLUDE_PRIM_BOOL
	#include GMOD_INCLUDE_PRIM_NULLPTR
	#include GMOD_INCLUDE_PRIM_VOID

	//// Chars ////

	#include GMOD_INCLUDE_PRIM_CHAR
	#include GMOD_INCLUDE_PRIM_WIDECHAR
	#include GMOD_INCLUDE_PRIM_SCHAR
	#include GMOD_INCLUDE_PRIM_UCHAR
	#include GMOD_INCLUDE_PRIM_UCHARLEAST8
	#include GMOD_INCLUDE_PRIM_UCHARLEAST16
	#include GMOD_INCLUDE_PRIM_UCHARLEAST32

	//// SInts ////

	#include GMOD_INCLUDE_PRIM_SHORTSINT
	#include GMOD_INCLUDE_PRIM_SINT
	#include GMOD_INCLUDE_PRIM_LONGSINT
	#include GMOD_INCLUDE_PRIM_LONGLONGSINT
	#include GMOD_INCLUDE_PRIM_MAXSINT
	#include GMOD_INCLUDE_PRIM_SINTPTR
	#include GMOD_INCLUDE_PRIM_SINT8
	#include GMOD_INCLUDE_PRIM_SINT16
	#include GMOD_INCLUDE_PRIM_SINT32
	#include GMOD_INCLUDE_PRIM_SINT64
	#include GMOD_INCLUDE_PRIM_SINTLEAST8
	#include GMOD_INCLUDE_PRIM_SINTLEAST16
	#include GMOD_INCLUDE_PRIM_SINTLEAST32
	#include GMOD_INCLUDE_PRIM_SINTLEAST64
	#include GMOD_INCLUDE_PRIM_SINTFAST8
	#include GMOD_INCLUDE_PRIM_SINTFAST16
	#include GMOD_INCLUDE_PRIM_SINTFAST32
	#include GMOD_INCLUDE_PRIM_SINTFAST64
	
	//// UInts ////

	#include GMOD_INCLUDE_PRIM_SHORTINT
	#include GMOD_INCLUDE_PRIM_UINT
	#include GMOD_INCLUDE_PRIM_UNSIGNEDLONGINTEGER
	#include GMOD_INCLUDE_PRIM_LONGLONGUINT
	#include GMOD_INCLUDE_PRIM_MAXUINT
	#include GMOD_INCLUDE_PRIM_UINTPTR
	#include GMOD_INCLUDE_PRIM_UINT8
	#include GMOD_INCLUDE_PRIM_UINT16
	#include GMOD_INCLUDE_PRIM_UINT32
	#include GMOD_INCLUDE_PRIM_UINT64
	#include GMOD_INCLUDE_PRIM_UINTLEAST8
	#include GMOD_INCLUDE_PRIM_UINTLEAST16
	#include GMOD_INCLUDE_PRIM_UINTLEAST32
	#include GMOD_INCLUDE_PRIM_UINTLEAST64
	#include GMOD_INCLUDE_PRIM_UINTFAST8
	#include GMOD_INCLUDE_PRIM_UINTFAST16
	#include GMOD_INCLUDE_PRIM_UINTFAST32
	#include GMOD_INCLUDE_PRIM_UINTFAST64

	//// Floats ////

	#include GMOD_INCLUDE_PRIM_FLOAT
	#include GMOD_INCLUDE_PRIM_DOUBLE
	#include GMOD_INCLUDE_PRIM_LONGDOUBLE
	
	
	#ifdef GMOD_LIB_EXT_INCLUDE_PRIM
		#include GMOD_LIB_EXT_INCLUDE_PRIM
	#endif
#endif